### PR TITLE
Remove a few files that are no longer used

### PR DESCRIPTION
**Pull request by c-w**
No functional change: just removing some unused files that may be confusing to developers and add overhead in larger-scale refactorings.

Also removing the deployment files since we're now deploying via [deis](https://github.com/CatalystCode/project-fortis-pipeline/tree/2c9ac8e214b21b696c0b651f866673a4a5502315/ops/deis-apps/fortis-interface).

### CODE REVIEW

**Review by erikschlegel — CHANGES_REQUESTED** [review]
We need to find a better solution for serving up the image assets. Until we do, can you add the image assets back to the repo.

**Review by erikschlegel — COMMENTED** [review]
Isnt public/index.html our main html file?

**Review by erikschlegel — COMMENTED** [review]
For example, public/images/OCHA_Logo.png is the main logo we render on the site.

**Comment by c-w** [comment]
Public is back ~~0249659~~ 5f8d77a

**Review by erikschlegel — APPROVED** [review]

**Pull request merged**
